# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "BenchmarkDotNet";
    version = "0.13.2";
    hash = "sha256-pPOfcWYc12nYw6e9Xdm9IWaYcaopoP2CursB9c2x7aQ=";
  })
  (fetchNuGet {
    pname = "BenchmarkDotNet.Annotations";
    version = "0.13.2";
    hash = "sha256-AWceHXlAviWayKQolyAskwjo5wduwJjYaJyr8smWIhc=";
  })
  (fetchNuGet {
    pname = "CommandLineParser";
    version = "2.4.3";
    hash = "sha256-pTyYP26uXXLe6ejCb/yVYpb23ad/Dkl2Ka8NWwQeiqk=";
  })
  (fetchNuGet {
    pname = "DotNet.ReproducibleBuilds";
    version = "1.2.25";
    hash = "sha256-Vl9RPq9vCO4bjulPZiOr3gDVKlr9vnuKIIX3KWlRxvw=";
  })
  (fetchNuGet {
    pname = "fantomas";
    version = "5.2.0-alpha-008";
    hash = "sha256-1egphbWXTjs2I5aFaWibFDKgu3llP1o32o1X5vab6v4=";
  })
  (fetchNuGet {
    pname = "FSharp.Collections.ParallelSeq";
    version = "1.2.0";
    hash = "sha256-2/3Bs9shlzkNGvR+m0R9Izb8UUb8VKO60dAlBDiIUls=";
  })
  (fetchNuGet {
    pname = "FsUnit";
    version = "6.0.0";
    hash = "sha256-q87WQf6MqGhzvaQ7WkkUlCdoE94DY0CD5PaXEj64A6M=";
  })
  (fetchNuGet {
    pname = "Iced";
    version = "1.17.0";
    hash = "sha256-6/5E5v5mqSG7yiE2zHUChZZeC47NRgLzQFD4+7bqKaU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "1.1.0";
    hash = "sha256-QYVojfqSZKbF8P6D/aacfxfumMaRUD9SEEQbzw73Bbc=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "2.6.2-beta2";
    hash = "sha256-hWlcoxSXAxBxhctuBnl0uD6KlCQyciZ9YepWEcAWS5Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "3.0.0";
    hash = "sha256-ucZQCNXYzt+I+8H7L8afvs1oNKq3NyD6Qn0M/8EP22A=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "3.0.0";
    hash = "sha256-IT1T1G4dyMCC85ypa5Ue1JkZC4Vex35yZR4PzO+Aa7U=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeCoverage";
    version = "17.10.0";
    hash = "sha256-yQFwqVChRtIRpbtkJr92JH2i+O7xn91NGbYgnKs8G2g=";
  })
  (fetchNuGet {
    pname = "Microsoft.Diagnostics.NETCore.Client";
    version = "0.2.251802";
    hash = "sha256-9ZH4rrfACzJP5oiarDW4cD2nczv1SNgZr4GW1J9hlUA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Diagnostics.Runtime";
    version = "2.2.332302";
    hash = "sha256-5R9xK0owZEhXsucqPKnPaTiwhXBnLo92L2AY7IjyxNg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Diagnostics.Tracing.TraceEvent";
    version = "3.0.2";
    hash = "sha256-BHuiTEkA76/9QIR9MG8SBhdExgKFFGd//2RjX8V3XJM=";
  })
  (fetchNuGet {
    pname = "Microsoft.DotNet.PlatformAbstractions";
    version = "3.1.6";
    hash = "sha256-RfM2qXiqdiamPkXr4IDkNc0IZSF9iTZv4uou/E7zNS0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "2.1.1";
    hash = "sha256-pnO6GdmnPJ8D4pmMpkxwgM4GggwGd2Uk+5s6OfJnhAg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "2.1.1";
    hash = "sha256-3DdHcNmy+JKWB4Q8ixzE4N/hUAvx2o4YlYal4Riwiyw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "2.1.1";
    hash = "sha256-FVdAa88PLAbWXTnEoa7AVSaC9AEjQ66LoxdtJ5nRIVk=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "2.1.1";
    hash = "sha256-BMU00QmmhtH3jP5cepJnoTrxrPESWeDU0i5UrIpIwGY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "2.1.1";
    hash = "sha256-HnEBmAhweBalCAeX+KZ4kEL3GXEVDBg6Uq4H4LJ56oo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "2.1.1";
    hash = "sha256-TzbYgz4EemrYKHMvB9HWDkFmq0BkTetKPUwBpYHk9+k=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "2.1.1";
    hash = "sha256-dCPA56Wv9cLuz720PmVbk2oXda1t9ZSAlP8/clDU93E=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "2.1.1";
    hash = "sha256-nbu2OeQGWeG8QKpoAOxIQ8aPzDbWHgbzLXh55xqeeQw=";
  })
  (fetchNuGet {
    pname = "Microsoft.NET.Test.Sdk";
    version = "17.10.0";
    hash = "sha256-rkHIqB2mquNXF89XBTFpUL2z5msjTBsOcyjSBCh36I0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.0.0";
    hash = "sha256-IEvBk6wUXSdyCnkj6tHahOJv290tVVT8tyemYcR0Yro=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.ObjectModel";
    version = "17.10.0";
    hash = "sha256-3YjVGK2zEObksBGYg8b/CqoJgLQ1jUv4GCWNjDhLRh4=";
  })
  (fetchNuGet {
    pname = "Microsoft.TestPlatform.TestHost";
    version = "17.10.0";
    hash = "sha256-+yzP3FY6WoOosSpYnB7duZLhOPUZMQYy8zJ1d3Q4hK4=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    hash = "sha256-K2tSVW4n4beRPzPu3rlVaBEMdGvWSv/3Q1fxaDh4Mjo=";
  })
  (fetchNuGet {
    pname = "NUnit";
    version = "4.1.0";
    hash = "sha256-srzj0lf2ReKw41TnigZwf8rqKKNzGRRVrgN3hR/vRjo=";
  })
  (fetchNuGet {
    pname = "NUnit3TestAdapter";
    version = "4.5.0";
    hash = "sha256-ER3ogl0L5FYyc6pVVPY1ch+AQxG/WgFcnWECnYQJPes=";
  })
  (fetchNuGet {
    pname = "Perfolizer";
    version = "0.2.1";
    hash = "sha256-nllshKuHU+1jSBfcTz8BTJTGr1TeCFvxjM4OPyLGSgQ=";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "6.0.0";
    hash = "sha256-uPetUFZyHfxjScu5x4agjk9pIhbCkt5rG4Axj25npcQ=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "1.5.0";
    hash = "sha256-BliqYlL9ntbMXo5d7NUrKXwYN+PqdyqDIS5bp4qVr7Q=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "5.0.0";
    hash = "sha256-GdwSIjLMM0uVfE56VUSLVNgpW0B//oCeSFj8/hSlbM8=";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "6.0.0";
    hash = "sha256-uZEf0a+9a2dqmzJS1Qxm3TR5ZxBHfeBLNO+q6ct5QWU=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.1";
    hash = "sha256-7JhQNSvE6JigM1qmmhzOX3NiZ6ek82R4whQNb+FpBzg=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.7.0";
    hash = "sha256-Fw/CSRD+wajH1MqfKS3Q/sIrUH7GN4K+F+Dx68UPNIg=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.7.0";
    hash = "sha256-V0Wz/UUoNIHdTGS9e1TR89u58zJjo/wPUWw6VaVyclU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "1.6.0";
    hash = "sha256-JJfgaPav7UfEh4yRAQdGhLZF1brr0tUWPl6qmfNWq/E=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.0";
    hash = "sha256-g9jIdQtXSAhY+ezQtYNgHEUoQR3HzznHs3JMzD9bip4=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.3";
    hash = "sha256-lnZMUqRO4RYRUeSO8HSJ9yBHqFHLVbmenwHWkIU20ak=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "5.0.0";
    hash = "sha256-neARSpLPUzPxEKhJRwoBzhPxK+cKIitLx7WBYncsYgo=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.5.0";
    hash = "sha256-Q+7R7EVSOtsXIzKjjfCnvfNul6AE1NxzJZirG0JCo6c=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
]
